### ISSUE TITLE
EditOrders does not calculate fees correct

### ISSUE THREAD

**Issue by Devel484** [Switcheo/carbon-js-sdk#185]
Calling the method editOrders sets the fee to 1swth rather than calculating it based on the count of orders.

`Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 100000000swth required: 200000000swth: insufficient fee`

**Comment by stevenkhong** [comment]
Thank you for the report, apparently we have hardcoded some of the signature options passed into the `CarbonWallet` when using the modules to create transactions (e.g. `sdk.order.editOrders`).

This has been fixed in 4455f004b7a13f28e9d1b8bd57a9d5b35a808b51.
