### ISSUE TITLE
EditOrder(s) require stopPrice to be set.

### ISSUE THREAD

**Issue by Devel484** [Switcheo/carbon-js-sdk#186]
The method editOrder(s) require stopPrice to be set to an actual BigNumber, null and undefined will result in an exception. 

Setting stopPrice = new BigNumber(0) seems to be a workaround

**Comment by stevenkhong** [comment]
Thank you for the report.

`OrderModule.CreateOrderParams` has been made optional in 4455f004b7a13f28e9d1b8bd57a9d5b35a808b51 with the appropriate fallback value.
