### ISSUE TITLE
[Bug] Error in react native 0.70.5

### ISSUE THREAD

**Issue by silkaynhe** [Switcheo/carbon-js-sdk#271]
[Bug] Error in react native 0.70.5
Error: Unable to resolve module @ledgerhq/devices/hid-framing from ./node_modules/@ledgerhq/hw-transport-webusb/lib/TransportWebUSB.js: @ledgerhq/devices/hid-framing could not be found within the project or in these directories: node_modules

**Comment by stevenkhong** [comment]
Hey @silkaynhe can you verify that you still get this error when you're using the latest version of the SDK? 
[v0.3.56](https://www.npmjs.com/package/carbon-js-sdk/v/0.3.56)

**Comment by silkaynhe** [comment]
Hey @stevenkhong The error is still on version v0.3.56
<img width="373" alt="error" src="https://user-images.githubusercontent.com/127747232/226533365-dac0b5d3-4a0b-4687-a19d-6a8ff8e95943.png">

**Comment by stevenkhong** [comment]
Seems like the issue is with the ledgerhq library, discussed here: https://github.com/LedgerHQ/ledger-live/issues/763

If you're using webpack4 and you don't really care about ledger functionality, a quick workaround is to pin the ledger library versions in `package.json`:
```
...
resolutions: {
    "@ledgerhq/hw-app-eth": "6.31.0",
    "@ledgerhq/hw-transport": "6.28.1",
    "@ledgerhq/hw-transport-webhid": "6.24.1",
    "@ledgerhq/hw-transport-webusb": "6.24.1",
}
...
```
